version: "3.6"

services:
  postgresimporter:
    image: romnn/postgresimporter
    restart: "no"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: example
    command:
      - --post-load=/post-load
      - --combine-tables
      - --exclude-regex="^.*sample.*$$"
      - /import
    volumes:
      - ${TRAIN_DATA}:/import:ro
      - ${TRAIN_DATA_HOOKS}:/post-load:ro