dist: trusty
sudo: required
osx_image: xcode9.4
language: java

cache:
  directories:
    - $HOME/.cache/bazel/_bazel_$USER/cache/repos/v1/content_addressable

env:
  global:
    - V=3.0.0
    - RUN_OPTS="--show_result=0 --noshow_progress --noshow_loading_progress --logging=0"

script: bazel test ${RUN_OPTS} ${TEST_TARGET} --test_output=errors --test_tag_filters="${TEST_FILTER}"

matrix:
  # It's ok to fail on osx as linux is the primary target
  allow_failures:
    - os: osx
  # Don't wait for osx tests to finish.
  # Mark the test run green as soon as the tests pass on linux.
  fast_finish: true
  include:
    # Linux: Smoke Tests
    - stage: Unit Tests
      name: Smoke Tests
      env: TEST_TARGET=":smoke"
      os: linux

    # OSX: Smoke Tests
    - stage: Unit Tests
      name: Smoke Tests
      env: TEST_TARGET=":smoke" TEST_FILTER=-docker
      os: osx

    # Linux: Unit Tests
    - stage: Unit Tests
      name: Unit Tests
      env: TEST_TARGET=":unit"
      os: linux

    # OSX: Unit Tests
    - stage: Unit Tests
      name: Unit Tests
      env: TEST_TARGET=":unit" TEST_FILTER=-docker
      os: osx

    # Linux: Integration Tests
    - stage: Integration Tests
      name: Integration Tests
      env: TEST_TARGET=":integration"
      os: linux

    # OSX: Integration Tests
    - stage: Integration Tests
      name: Integration Tests
      env: TEST_TARGET=":integration" TEST_FILTER=-docker
      os: osx

    - stage: deploy
      name: Deploy to GitHub Pages
      script: echo "Deploying to GitHub Pages"
      before_deploy: openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
      os: osx
      deploy:
        provider: pages
        local_dir: web
        skip_cleanup: true
        verbose: true
        keep_history: true
        edge: true
        deploy_key: deploy_key
        on:
          branch: dev

before_install:
  - rm .bazelrc
  - mv .bazelrc.ci .bazelrc
  - echo "Installing bazel"
  - OS=linux
  - ARCH=x86_64
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - CI_BASE="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-$ARCH/lastSuccessfulBuild/artifact/output/ci"
  - CI_ARTIFACT="bazel--installer.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - if [[ "$V" == "HEAD" ]]; then CI_ARTIFACT="`wget -qO- $CI_BASE | grep -o 'bazel-[-_a-zA-Z0-9\.]*-installer.sh' | uniq`"; fi
  - if [[ "$V" == "HEAD" ]]; then URL="$CI_BASE/$CI_ARTIFACT"; fi
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

stages:
  - name: Unit Tests
  # Integration Tests require Unit Tests to succeed
  - name: Integration Tests
  - name: Deploy to GitHub Pages
