branches:
  only:
    - /^*$/
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
   - os: linux
     arch: amd64
   # Skip testing for ARM64 as this would require compiling
   # protoc-gen-grpc-web manually
   # - os: linux
   #   arch: arm64
   #   addons:
   #     apt:
   #       packages:
   #         - maven
   - os: osx
     # osx does not support openjdk<9
     jdk: openjdk11
   - os: windows
     # windows does not support building java out of the box
     language: shell

services:
  - docker

language: java
jdk:
  - openjdk8
  - openjdk11

before_install:
  # Manually install openjdk and maven when on windows
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install openjdk8 maven ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmd.exe //c "RefreshEnv.cmd & iisexpress.exe" ; fi
  # - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ci/RefreshEnv.sh ; fi
  # - if [ "$TRAVIS_OS_NAME" = "windows" ]; then RefreshEnv ; fi

before_script:
  # Try to start pgadmin via docker
  - deployment/dev/devenv.sh -p test up -d pgadmin

script:
  # Test docker compose regressions
  # - (exit $(docker inspect -f "{{.State.ExitCode}}" test_pgadmin_1))
  - docker ps | grep -q pgadmin
  # Check if the project builds successfully
  - mvn clean verify
