branches:
  only:
    - /^*$/
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
   - os: linux
     arch: amd64
   # Skip testing for ARM64 as this would require compiling
   # protoc-gen-grpc-web manually
   # - os: linux
   #   arch: arm64
   #   addons:
   #     apt:
   #       packages:
   #         - maven
   - os: osx
     # osx does not support openjdk<9
     jdk: openjdk11
   # Disable windows completely because it does not make sense
   #- os: windows
   #  # windows does not support building java out of the box
   #  language: shell

services:
  - docker

language: java
jdk:
  - openjdk8
  - openjdk11

before_install:
  # Manually install openjdk and maven when on windows
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install openjdk8 maven docker-desktop docker-compose ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmd.exe //c "RefreshEnv.cmd" ; fi

before_script:
  # Try to start pgadmin via docker
  # As windows server cannot run linux docker containers we can only test this on linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then deployment/dev/devenv.sh -p test up -d pgadmin ; fi

script:
  # Test docker compose regressions
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then docker ps | grep -q pgadmin ; fi
  # Check if the project builds successfully
  - mvn clean verify
