test_suite(
    name = "all",
    tests = [
        "//core/src/test/java/org/bptlab/cepta/live_planned_trains:all",
        "//core/src/test/java/org/bptlab/cepta/weather-tests:all",
        "//core/src/test/java/org/bptlab/cepta/data_to_database:all",
    ],
)
