version: "3.6"
services:
  core:
    build:
      context: ../../../
      dockerfile: deployment/common/java.exec.dockerfile
      args:
        MODULE: core

    # network_mode: host
    # ports:
    #  - ${CEPTA_WEBUI_BACKEND_PORT}:8082