version: "3.6"
services:
  envoy:
    image: envoyproxy/envoy
    ports:
      - ${CEPTA_ENVOY_ADMIN_PORT}:9901
      - ${CEPTA_ENVOY_INGRESS_PORT}:80
      - ${CEPTA_ENVOY_GRPC_PORT}:81
    environment:
      ENVOY_HOST: ${ENVOY_HOST}
    volumes:
      - ../envoy.yaml:/etc/envoy/envoy.yaml.tmpl:ro
      - ../../common/prepare-envoy.sh:/prepare.sh:ro
    entrypoint: ["bin/sh", "/prepare.sh"]
    network_mode: host
    env_file: .env
    command:
      - envoy
      - -c /etc/envoy/envoy.yaml