version: "3.6"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    # network_mode: host
    ports:
      - ${CEPTA_ZOOKEEPER_PORT}:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:2.3.0
    # network_mode: host
    ports:
      - ${CEPTA_KAFKA_PORT}:9092
      - 29092:29092
    volumes:
      - kafka_data:/bitnami
    environment:
      # Use "zookeeper:2181" for bridged networks, "locahost:2181" for network mode
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:${CEPTA_ZOOKEEPER_PORT}
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager
    # network_mode: host
    ports:
      - ${CEPTA_KAFKA_MANAGER_PORT}:9000
    environment:
      # Use "zookeeper:2181" for bridged networks, "locahost:2181" for network mode
      ZK_HOSTS: zookeeper:${CEPTA_ZOOKEEPER_PORT}
      KM_VERSION: 2.3.0

  kafdrop:
    image: thomsch98/kafdrop
    # network_mode: host
    ports:
      - ${CEPTA_KAFDROP_PORT}:9001
    environment:
      # Use "zookeeper:2181" for bridged networks, "locahost:2181" for network mode
      ZK_HOSTS: zookeeper:${CEPTA_ZOOKEEPER_PORT}
      LISTEN: ${CEPTA_KAFDROP_PORT}
 
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
