version: "3.6"
services:
    mongodb:
        image: "mongo"
        volumes:
            - mongodb_data:/data/db
        expose:
            - 27017
        ports:
            - ${CEPTA_MONGODB_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

volumes:
    mongodb_data:
        driver: local
