version: "3.6"

services:
  postgres_exporter:
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:example@postgres:5432/postgres?sslmode=disable"
      # DATA_SOURCE_PASS: example
      # DATA_SOURCE_USER: postgres
      # DATA_SOURCE_URI: postgresql://postgres:5432/postgres?sslmode=disable

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../../../deployment/common/prometheus/prometheus.config.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention=12h
    ports:
      - ${CEPTA_PROMETHEUS_PORT}:9090

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - prometheus
    ports:
      - ${CEPTA_GRAFANA_PORT}:3000
    volumes:
      - ../../../deployment/common/grafana/provisioning:/etc/grafana/provisioning
      - ../../../deployment/common/grafana/config.ini:/etc/grafana/config.ini
      - ../../../deployment/common/grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  prometheus_data: {}
  grafana_data: {}
