version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3.8.1-management
    # environment:
      # RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      # RABBITMQ_DEFAULT_USER: "rabbitmq"
      # RABBITMQ_DEFAULT_PASS: "rabbitmq"
      # RABBITMQ_DEFAULT_VHOST: "/"
    expose:
      - 5672
    ports:
      - ${CEPTA_RABBITMQ_PORT}:5672
    volumes:
      - ../../common/rabbitmq/rmq_enabled_plugins.txt:/etc/rabbitmq/enabled_plugins
      # - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      # - ./data:/var/lib/rabbitmq:rw
      # - ./definitions.json:/opt/definitions.json:ro

