version: "3.6"

services:
  postgresimporter:
    image: romnn/postgresimporter
    restart: "no"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: example
    command:
      - --combine-tables
      - --exclude-regex="^.*sample.*$$"
      - /import
    volumes:
      - "~/bp/Train\ Data/2019\ -\ 01:/import"
      # - ../hooks/reset-db.sql:/reset-db.sql
      # - ../hooks/post-dump.sql:/post-dump.sql
      # - --disable-import
      # - --disable-unzip
      # - --post-dump=/post-dump.sql
      # - --pre-dump=/reset-db.sql