/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package connectors.consumer_producer;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WeatherData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5610452063737503026L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherData\",\"namespace\":\"connectors.consumer_producer\",\"fields\":[{\"name\":\"City\",\"type\":\"string\"},{\"name\":\"Temperature\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WeatherData> ENCODER =
      new BinaryMessageEncoder<WeatherData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WeatherData> DECODER =
      new BinaryMessageDecoder<WeatherData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<WeatherData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<WeatherData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WeatherData>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this WeatherData to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a WeatherData from a ByteBuffer. */
  public static WeatherData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public String City;
  @Deprecated public int Temperature;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeatherData() {}

  /**
   * All-args constructor.
   * @param City The new value for City
   * @param Temperature The new value for Temperature
   */
  public WeatherData(String City, java.lang.Integer Temperature) {
    this.City = City;
    this.Temperature = Temperature;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return City;
    case 1: return Temperature;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: City = (String)value$; break;
    case 1: Temperature = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'City' field.
   * @return The value of the 'City' field.
   */
  public String getCity() {
    return City;
  }

  /**
   * Sets the value of the 'City' field.
   * @param value the value to set.
   */
  public void setCity(String value) {
    this.City = value;
  }

  /**
   * Gets the value of the 'Temperature' field.
   * @return The value of the 'Temperature' field.
   */
  public java.lang.Integer getTemperature() {
    return Temperature;
  }

  /**
   * Sets the value of the 'Temperature' field.
   * @param value the value to set.
   */
  public void setTemperature(java.lang.Integer value) {
    this.Temperature = value;
  }

  /**
   * Creates a new WeatherData RecordBuilder.
   * @return A new WeatherData RecordBuilder
   */
  public static WeatherData.Builder newBuilder() {
    return new WeatherData.Builder();
  }

  /**
   * Creates a new WeatherData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WeatherData RecordBuilder
   */
  public static WeatherData.Builder newBuilder(WeatherData.Builder other) {
    return new WeatherData.Builder(other);
  }

  /**
   * Creates a new WeatherData RecordBuilder by copying an existing WeatherData instance.
   * @param other The existing instance to copy.
   * @return A new WeatherData RecordBuilder
   */
  public static WeatherData.Builder newBuilder(WeatherData other) {
    return new WeatherData.Builder(other);
  }

  /**
   * RecordBuilder for WeatherData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherData>
    implements org.apache.avro.data.RecordBuilder<WeatherData> {

    private String City;
    private int Temperature;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(WeatherData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.City)) {
        this.City = data().deepCopy(fields()[0].schema(), other.City);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Temperature)) {
        this.Temperature = data().deepCopy(fields()[1].schema(), other.Temperature);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing WeatherData instance
     * @param other The existing instance to copy.
     */
    private Builder(WeatherData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.City)) {
        this.City = data().deepCopy(fields()[0].schema(), other.City);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Temperature)) {
        this.Temperature = data().deepCopy(fields()[1].schema(), other.Temperature);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'City' field.
      * @return The value.
      */
    public String getCity() {
      return City;
    }

    /**
      * Sets the value of the 'City' field.
      * @param value The value of 'City'.
      * @return This builder.
      */
    public WeatherData.Builder setCity(String value) {
      validate(fields()[0], value);
      this.City = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'City' field has been set.
      * @return True if the 'City' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'City' field.
      * @return This builder.
      */
    public WeatherData.Builder clearCity() {
      City = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Temperature' field.
      * @return The value.
      */
    public java.lang.Integer getTemperature() {
      return Temperature;
    }

    /**
      * Sets the value of the 'Temperature' field.
      * @param value The value of 'Temperature'.
      * @return This builder.
      */
    public WeatherData.Builder setTemperature(int value) {
      validate(fields()[1], value);
      this.Temperature = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Temperature' field has been set.
      * @return True if the 'Temperature' field has been set, false otherwise.
      */
    public boolean hasTemperature() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Temperature' field.
      * @return This builder.
      */
    public WeatherData.Builder clearTemperature() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WeatherData build() {
      try {
        WeatherData record = new WeatherData();
        record.City = fieldSetFlags()[0] ? this.City : (String) defaultValue(fields()[0]);
        record.Temperature = fieldSetFlags()[1] ? this.Temperature : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WeatherData>
    WRITER$ = (org.apache.avro.io.DatumWriter<WeatherData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WeatherData>
    READER$ = (org.apache.avro.io.DatumReader<WeatherData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
