notifiers:
  - name: notification-channel-1
    type: telegram
    uid: notifier1
    org_id: 1
    is_default: true
    send_reminder: true
    frequency: 4h
    disable_resolve_message: false
    settings:
      bottoken: "XXX"
      chatid: "xoxb"