filegroup(
    name = "auxiliary",
    srcs = [
        "//auxiliary/producers/mockkafkaproducer",
        "//auxiliary/producers/traindataproducer",
    ],
    visibility = ["//visibility:public"],
)