filegroup(
    name = "auxiliary",
    srcs = [
        "//auxiliary/producers/generator/notifications",
        "//auxiliary/producers/generator/transports",
        "//auxiliary/producers/replayer",
    ],
    visibility = ["//visibility:public"],
)
