load("@rules_proto//proto:defs.bzl", "proto_library")

filegroup(
    name = "models",
    srcs = [
        "//models/constants",
        "//models/events",
        "//models/gql",
        "//models/grpc",
    ],
    visibility = ["//visibility:public"],
)

